### ISSUE TITLE
Few UX improvements request

### ISSUE THREAD

**Issue by thongta** [compojoom/jedchecker#19]
Hi there,

The component would be much more helpful and saving time by:
- Able to run Check for a specific folder rather than [upload, unzip and check] process. I'm developer, using this component to check my extensions on dev-progress and it's annoying to make symlink over and over again for check things.
- Add a toggle to Info block which is probably not necessary - http://awesomescreenshot.com/0c64290a5b
- Mark Error as RED, Warning as ORANGE and Info as BLUE. Currently, only Info marked as BLUE, Errors & Warnings are still in BLACK.

Hope that helps. If I can contribute codes to this useful, let me know.

**Comment by compojoom** [comment]
https://github.com/compojoom/jedchecker#checking-on-existing-files-and-folders - adding folders should be working

**Comment by JazParkyn** [comment]
Closing inactive issue.

Folder checks and coloured warnings have been implemented. Toggle switch is coming soon.
