### ISSUE TITLE
PHP version inconsistent check during installation

### ISSUE THREAD

**Issue by demis-palma** [compojoom/jedchecker#33]
In the installation script (file: script.php, method: preflight) it checks for the presence of PHP 5.3.1 or newer, but if an older version is detected, it notices that the version 5.3.6 or newer is required. :frowning:

So what is the actual requirement, PHP 5.3.1 or 5.3.6?

Considering that the minimum requirements to run Joomla itself is PHP 5.3.10, and that this extension does not work as stand-alone, the PHP version check could be safely removed at all. It probably comes from the 2.5 release.

**Comment by JazParkyn** [comment]
We should match the Joomla minimum requirements. Just in case somebody tries to install on J2.5
